version: '3'

services:
 db:
  image: mysql
  hostname: mysql_server
  restart: on-failure
  env_file: .env
  volumes:
   - $PWD/database:/docker-entrypoint-initdb.d
 src:
  #image: python:3.4-alpine
  build: .
  depends_on: 
   - db
  volumes:
   - $PWD/app:/code
  ports:
   - "5000:5000"
  command: ["appFlask.py"]
  links:
   - db:mysql_server
  #command: python
