---
version: "2.4"

services:

  server:
    image: httpd:latest
    hostname: "server"
    networks:
      - demo
    volumes:
      - ./index.html:/usr/local/apache2/htdocs/index.html

  client:
    build: .
    hostname: "client"
    depends_on:
      - "server"
    networks:
      - demo

networks:
  demo:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1
